# Generated by Django 4.2 on 2023-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('name_slug', models.SlugField(null=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=75, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('long_desc', models.TextField(blank=True, max_length=2000, null=True)),
                ('course_image', models.ImageField(default='default_course.jpg', null=True, upload_to='CoursesImages')),
                ('original_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], default='English', max_length=20, null=True)),
                ('author_image', models.ImageField(default='default_author.jpg', null=True, upload_to='AuthorsImages')),
            ],
        ),
    ]
